export const customStyles = {
  stepIndicatorSize: 25,
  currentStepIndicatorSize: 30,
  separatorStrokeWidth: 2,
  currentStepStrokeWidth: 3,
  stepStrokeCurrentColor: "#605bff",
  stepStrokeWidth: 3,
  stepStrokeFinishedColor: "#605bff",
  stepStrokeUnFinishedColor: "#aaaaaa",
  separatorFinishedColor: "#605bff",
  separatorUnFinishedColor: "#aaaaaa",
  stepIndicatorFinishedColor: "#605bff",
  stepIndicatorUnFinishedColor: "#ffffff",
  stepIndicatorCurrentColor: "#ffffff",
  stepIndicatorLabelFontSize: 13,
  currentStepIndicatorLabelFontSize: 13,
  stepIndicatorLabelCurrentColor: "#605bff",
  stepIndicatorLabelFinishedColor: "#ffffff",
  stepIndicatorLabelUnFinishedColor: "#aaaaaa",
  labelColor: "#999999",
  labelSize: 13,
  currentStepLabelColor: "#605bff",
};
